--[[
QuestTogether Communication Layer (No AceComm/AceSerializer)

This file handles addon-to-addon messages with native WoW APIs:
- Receive via CHAT_MSG_ADDON
- Send via C_ChatInfo.SendAddonMessage

Message format on the wire:
  <COMMAND>|<PAYLOAD>

Payload encoding strategy:
- Simple strings use percent-encoding (EscapePayload/UnescapePayload).
- Quest tracker snapshots use a custom compact format because they are nested tables.
]]

local QuestTogether = _G.QuestTogether

-- Split helper that uses a plain-string delimiter (no Lua pattern magic).
local function SplitByDelimiter(text, delimiter)
	local pieces = {}
	if text == nil or text == "" then
		return pieces
	end

	local startIndex = 1
	while true do
		local delimiterIndex = string.find(text, delimiter, startIndex, true)
		if not delimiterIndex then
			pieces[#pieces + 1] = string.sub(text, startIndex)
			break
		end
		pieces[#pieces + 1] = string.sub(text, startIndex, delimiterIndex - 1)
		startIndex = delimiterIndex + #delimiter
	end

	return pieces
end

-- Percent-encode arbitrary text for safe transport in our delimiter-based format.
function QuestTogether:EscapePayload(value)
	local text = tostring(value or "")
	return (text:gsub("([^%w%-_%.~])", function(character)
		return string.format("%%%02X", string.byte(character))
	end))
end

-- Reverse of EscapePayload.
function QuestTogether:UnescapePayload(value)
	local text = tostring(value or "")
	return (text:gsub("%%(%x%x)", function(hex)
		return string.char(tonumber(hex, 16))
	end))
end

-- Encode quest tracker data for UPDATE_QUEST_TRACKER.
-- Structure encoded per quest:
--   questId,title,objectiveCount,objective1,objective2,...
-- Quest records are separated by semicolons.
function QuestTogether:EncodeQuestTracker(tracker)
	local encodedQuests = {}
	for questId, questData in pairs(tracker or {}) do
		local objectives = (questData and questData.objectives) or {}
		local objectiveCount = #objectives
		local row = {
			tostring(questId),
			self:EscapePayload((questData and questData.title) or ""),
			tostring(objectiveCount),
		}
		for index = 1, objectiveCount do
			row[#row + 1] = self:EscapePayload(objectives[index] or "")
		end
		encodedQuests[#encodedQuests + 1] = table.concat(row, ",")
	end
	return table.concat(encodedQuests, ";")
end

-- Decode the format generated by EncodeQuestTracker back into a Lua table.
function QuestTogether:DecodeQuestTracker(payload)
	local tracker = {}
	if payload == nil or payload == "" then
		return tracker
	end

	local questRows = SplitByDelimiter(payload, ";")
	for _, rowText in ipairs(questRows) do
		local fields = SplitByDelimiter(rowText, ",")
		local questId = tonumber(fields[1])
		local title = self:UnescapePayload(fields[2] or "")
		local objectiveCount = tonumber(fields[3]) or 0

		if questId then
			local questData = {
				title = title,
				objectives = {},
			}
			for objectiveIndex = 1, objectiveCount do
				questData.objectives[objectiveIndex] = self:UnescapePayload(fields[3 + objectiveIndex] or "")
			end
			tracker[questId] = questData
		end
	end

	return tracker
end

function QuestTogether:SerializeWireMessage(command, payload)
	local encodedPayload
	if command == "UPDATE_QUEST_TRACKER" then
		encodedPayload = self:EncodeQuestTracker(payload or {})
	else
		encodedPayload = self:EscapePayload(payload or "")
	end
	return tostring(command) .. "|" .. tostring(encodedPayload)
end

function QuestTogether:DeserializeWireMessage(message)
	if not message then
		return nil, nil
	end

	local command, payload = string.match(message, "^([^|]+)|?(.*)$")
	if not command or command == "" then
		return nil, nil
	end

	if command == "UPDATE_QUEST_TRACKER" then
		return command, self:DecodeQuestTracker(payload)
	end
	return command, self:UnescapePayload(payload)
end

-- Broadcast a command to the player's current group channel.
function QuestTogether:Broadcast(command, payload)
	if not self.isEnabled then
		return false
	end

	local channel = self:GetBestAddonChannel()
	if not channel then
		return false
	end

	local wireMessage = self:SerializeWireMessage(command, payload)
	self.API.SendAddonMessage(self.commPrefix, wireMessage, channel)
	return true
end

-- CHAT_MSG_ADDON event handler.
function QuestTogether:CHAT_MSG_ADDON(_, prefix, message, channel, sender)
	self:OnCommReceived(prefix, message, channel, sender)
end

function QuestTogether:OnCommReceived(prefix, message, channel, sender)
	if prefix ~= self.commPrefix then
		return
	end
	if self:IsSelfSender(sender) then
		return
	end

	local command, payload = self:DeserializeWireMessage(message)
	if not command then
		return
	end

	local handler = self[command]
	if type(handler) ~= "function" then
		self:Debug("No handler for command: " .. tostring(command))
		return
	end

	local ok, err = pcall(handler, self, payload, sender, channel)
	if not ok then
		self:Print("Error handling command " .. tostring(command) .. ": " .. tostring(err))
	end
end

--[[
Command handlers
]]

function QuestTogether:CMD(text, sender)
	if not text or text == "" then
		return
	end

	self:Debug("CMD(" .. tostring(text) .. ") from " .. tostring(sender))

	if DEFAULT_CHAT_FRAME and DEFAULT_CHAT_FRAME.editBox then
		DEFAULT_CHAT_FRAME.editBox:SetText(text)
		ChatEdit_SendText(DEFAULT_CHAT_FRAME.editBox, 0)
		DEFAULT_CHAT_FRAME.editBox:SetText("")
	else
		self:Print(tostring(sender) .. " sent command: " .. tostring(text))
	end
end

function QuestTogether:EMOTE(emoteToken, sender)
	if not emoteToken or emoteToken == "" then
		return
	end

	-- Local-only gate: if this client has emotes disabled, do nothing.
	if not self:GetOption("doEmotes") then
		self:Debug("Ignoring incoming emote because doEmotes is disabled.")
		return
	end

	local token = emoteToken
	local faction = self.API.GetFaction()

	if self.API.IsMounted() and token == "mountspecial" then
		self.API.DoEmote("mountspecial")
		return
	end

	if token == "forthealliance" or token == "forthehorde" then
		if faction == "Alliance" then
			self.API.DoEmote("forthealliance", sender)
		elseif faction == "Horde" then
			self.API.DoEmote("forthehorde", sender)
		end
		return
	end

	-- If we receive a restricted emote token we cannot use right now, reroll to a safe one.
	if token == "mountspecial" or token == "forthealliance" or token == "forthehorde" then
		repeat
			local randomIndex = self.API.Random(1, #self.completionEmotes)
			token = self.completionEmotes[randomIndex]
		until token ~= "mountspecial" and token ~= "forthealliance" and token ~= "forthehorde"
	end

	self.API.DoEmote(token, sender)
end

function QuestTogether:UPDATE_QUEST_TRACKER(trackerData, sender)
	if type(trackerData) ~= "table" then
		return
	end
	self.db.global.questTrackers[sender] = trackerData
end

function QuestTogether:SUPER_TRACK()
	self:Debug("SUPER_TRACK is not implemented.")
end
